### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by vladfaust** [veelenga/lua.cr#30]
Hello,

Very nice bindings, thanks! However, I've got a small issue. On Ubuntu, there is no `liblua` available via `apt install`. I can install `liblua5.3-dev` instead, for example. It works perfectly if I change this line:

https://github.com/veelenga/lua.cr/blob/0f493dbbc7e70c47bc14f6c887df95b9e86a959a/src/lua/liblua.cr#L1

to `@[Link("lua5.3")]` instead. Which is OK, but requires to change the source code of the shard. What are my options here if I don't want to modify the shard code?

I tried writing these lines in my app code:

```crystal
require "lua"

@[Link("lua5.3")]
lib LibLua
end
```

But this did not help, the linker was still complaining about the missing `liblua` development package.

**Comment by straight-shoota** [comment]
As a simple workaround, you could make a symlink from `liblua` to `liblua5.4-dev`.

But fixing this issue is a use case for https://forum.crystal-lang.org/t/rfc-link-configuration/546/11

**Comment by veelenga** [comment]
Thanks.

Sorry, this shard is a bit abounded. But, if there is anything can be done in this repo to fix the issue, I can proceed.

**Comment by veelenga** [comment]
Closing it in favor of the suggestion above.
