### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jwoertink** [veelenga/lua.cr#31]
I know it's been a while since you've messed with this, but hoping you know... 

I have a lua file that looks like

```lua
-- settings.lua
manifest = "manifest.lua"
```

If I run 

```crystal
lua = Lua.load
result = lua.run(File.new("./settings.lua"))
raise result.inspect
```

I get `Unhandled exception: nil (Exception)`. However, if I add a `return manifest` to the end of that lua file, I'll get the `Unhandled exception: "manifest.lua" (Exception)`. 

Is there a way to get the values from the lua file without having to explicitly return at the end of them?

**Comment by veelenga** [comment]
Hey. Sorry for the late response.

No, there is no way of doing that (at least using this binding). You need to explicitly return the values from the file (or a lua function) to pass the result to the stack.

**Comment by jwoertink** [comment]
ah, ok. Thanks!
