### ISSUE TITLE
Support for Lua 5.4

### ISSUE THREAD

**Issue by reiswindy** [veelenga/lua.cr#35]
The return value from `lua_version` was changed from a pointer in 5.3 to a `lua_Number` in 5.4, but `LibLua.version` assumes it is always a pointer, so it will fail to run:

```
Unhandled exception: Lua 0.0 not supported. Try Lua 5.3 or higher. (Lua::RuntimeError)
  from lib/lua/src/lua/stack/util.cr:33:9 in 'check_lua_supported'
  from lib/lua/src/lua/stack.cr:42:7 in 'initialize'
  from lib/lua/src/lua/stack.cr:34:7 in 'initialize'
  from lib/lua/src/lua/stack.cr:33:5 in 'initialize'
  from lib/lua/src/lua/stack.cr:33:5 in 'new'
```

Is it possible to make a branch for each version?

**Comment by veelenga** [comment]
Sounds good, however, I would probably rather drop support for Lua 5.3 in favor of 5.4.

@reiswindy Do you feel confident to create a PR to support Lua 5.4?

**Comment by reiswindy** [comment]
Not very confident. Made some of the changes but many of the tests broke, and I don't know enough about the API to fix them.

**Comment by veelenga** [comment]
Okay, thanks. I will try to update it soon.

**Comment by reiswindy** [comment]
Took another jab at this, and managed to make almost all tests pass, but there's 5 tests related to class_support that are not passing.

```
Failed examples:

crystal spec spec/lua/stack/callable_support_spec.cr:6 # Lua::StackMixin::ClassSupport #pushobject test lua callable instance variables
crystal spec spec/lua/stack/callable_support_spec.cr:19 # Lua::StackMixin::ClassSupport #pushobject test lua callable instance methods
crystal spec spec/lua/stack/callable_support_spec.cr:33 # Lua::StackMixin::ClassSupport #pushobject test lua callable instance method with callable arg
crystal spec spec/lua/stack/callable_support_spec.cr:47 # Lua::StackMixin::ClassSupport #pushobject create new callable instance from Lua
crystal spec spec/lua/stack/callable_support_spec.cr:63 # Lua::StackMixin::ClassSupport #pushobject test lua callable subclass
```

I tried running them with lua5.3 and they were still failing, so they probably stopped working with one of crystal's updates.

**Comment by reiswindy** [comment]
Closing issue now that support was added. Thanks!
